stages:
  get_ingredient_links:
    cmd: python stages/01_get_ingredient_links.py
    deps:
      - stages/01_get_ingredient_links.py
    outs:
      - cache/ingredient_page_links.json

  get_pdf_links:
    cmd: python stages/02_get_pdf_links.py
    deps:
      - stages/02_get_pdf_links.py
      - cache/ingredient_page_links.json
    outs:
      - cache/all_pdf_links.json
  
  download_pdfs:
    cmd: python stages/03_download_pdfs.py
    deps:
      - stages/03_download_pdfs.py
      - cache/all_pdf_links.json
    outs:
      - brick/cir_reports_pdf
